### ISSUE TITLE
`new_page` 在初始化的问题

### ISSUE THREAD

**Issue by vvtommy** [fordlee404/generator-webapp-kit#10]
在 `yo webapp-kit:new_page` 的时候，会按照选择创建三个新文件，分别是一个 js 文件、一个 scss 文件和一个 HTML 文件。
js 初始文件如下

``` javascript
/* global window,require,module */
'use strict'
```

在这个 generator 中，`.(js|jsx)` 都是通过 [Babel](http://babeljs.io/) 编译过的，也就是都支持 ES6(harmony)。我想目前看来这个初始文件应该没有多少需要改进的地方（当然除了 #8 ）。

scss 目前是空文件。首先，cssmin 会编译一份 `core.min.css` 将所有 `plugins` 的样式表按照预先设计的顺序合并。所以该 scss 文件的依赖是在 HTML 中解决的，所以并不需要 import 这个 `core.min.css`。那么需要提前import 的就只有 compass 所提供的 mixins 了。另外在文件中明确字符集也是需要做的。那么在项目中所设计结构和顺序就必须在 Gruntfile 中自己做了。**这部分使用体验应该会很操蛋**。

HTML 目前也是只提供空文件。觉得要改进的部分有这么几点:
1. 是不是需要基本的 HTML 结构。因为存在 include-replace ，而且在开发多页面的应用时，公共的组件一定存在。在 generator 中要体现公共组件，那只需要对脚手架进行设计。有这样的情况存在，初始化一个 HTML 结构是不是有必要就需要考虑了。
2. `core.min.css` 、webpack 入口等，这些都是 generator 可以获取的
3. usemin 的文件标签

**Comment by fordlee404** [comment]
`new_page`时HTML应该有基本的结构。并且在项目初始化时，还需要完善一下项目的基本HTML结构文件，现在都是一些空目录。

**Comment by vvtommy** [comment]
但是就如我上面说到的， include-replace 如果使用的话，创建的基本结构就需要全部删掉。更麻烦

**Comment by fordlee404** [comment]
`include-replace`是HTML之间的相互调用，Gruntfile中配置并不多，为什么要删除创建的基本结构？

**Comment by fordlee404** [comment]
这个sub generator 在v2.0.0版本中已经被移除，所以关闭这个issue
