### ISSUE TITLE
关于模板变量的设计

### ISSUE THREAD

**Issue by vvtommy** [fordlee404/generator-webapp-kit#7]
首先，模板变量应该放到一个独立的文件中，而不是在不得不写的很长的 Gruntfile 中。

另外，用户的视点到底应该主要集中在提供的命令或者子命令上，还是这些「独立的配置文件」中，例如 `.webpack_entry.json`,`.webpack_alias.json`

**Comment by fordlee404** [comment]
我觉得应该专注点应该放在这些配置文件上，省去了开发各种命令及命令相关的文档，更灵活。
